aragon/osx-commons

README.md, subgraph/README.md
=> chore/ OS-704 Add security contact to the readme(s)

contracts/CHANGELOG.md, subgraph/CHANGELOG.md
Task ID: [OS-822](https://aragonassociation.atlassian.net/browse/OS-822)
[OS-822]: https://aragonassociation.atlassian.net/browse/OS-822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: maintained changelogs

subgraph/.eslintrc.yml, subgraph/src/ids/balance.ts, subgraph/src/ids/transfer.ts, subgraph/tests/ids/balance.test.ts, subgraph/tests/ids/transfer.test.ts
Task ID: [OS-585](https://aragonassociation.atlassian.net/browse/OS-585)
[OS-585]: https://aragonassociation.atlassian.net/browse/OS-585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feature: abstracted balance and transfer IDs

contracts/package.json, contracts/yarn.lock
Bump OSX dependencies and OZ to match with https://github.com/aragon/osx/pull/500.
Task: [OS-910](https://aragonassociation.atlassian.net/browse/OS-910)
[OS-910]: https://aragonassociation.atlassian.net/browse/OS-910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> build: bump dependencies

.github/workflows/packages-release.yml, .github/workflows/reusable-check-tag.yml
=> Fix: Reusable check tag workflow

contracts/CHANGELOG.md, contracts/package.json, sdk/CHANGELOG.md, sdk/package.json, subgraph/CHANGELOG.md, subgraph/package.json
=> osx-commons-subgraph v0.0.1-alpha.0

.github/workflows/contracts-publish.yml, .github/workflows/reusable-publish.yml, .github/workflows/sdk-publish.yml, .github/workflows/subgraph-publish.yml
=> fix publish worflow

.github/workflows/subgraph-publish.yml
@josemarinas forgot to add the release tag on the previous PR, bravo 👏 👏 
Task ID: None
=> osx-commons-subgraph release version 0.0.1

.github/workflows/reusable-check-tag.yml
Fix regex pattern in reusable check tag workflow
=> Fix: Regex pattern in reusable check workflow

.github/workflows/reusable-check-tag.yml
Yet another PR trying to fix this :)
=> Fix: Typo in release worflow

subgraph/CHANGELOG.md, subgraph/package.json, subgraph/src/ids/index.ts, subgraph/src/index.ts, subgraph/src/mocks/index.ts, subgraph/src/mocks/token.ts, subgraph/src/utils/index.ts
Add multiple index.ts files and add the missing exports to the main intex.ts file
=> Fix: Add missing exports

.github/workflows/configs-publish.yml, .github/workflows/reusable-publish.yml
cicd: fixes release not generation
=> cicd: fixes publish workflows release note generation

subgraph/CHANGELOG.md, subgraph/package.json, subgraph/src/ids/callbacks.ts, subgraph/src/ids/dao.ts, subgraph/src/ids/ids.ts, subgraph/src/ids/index.ts, subgraph/src/ids/permissions.ts, subgraph/src/ids/plugin.ts, subgraph/src/ids/proposal.ts, subgraph/src/utils/constants.ts, subgraph/tests/ids/permissions.test.ts
Use generic functions to convert to entity id
Task ID: [OS-737](https://aragonassociation.atlassian.net/browse/OS-737)
[OS-737]: https://aragonassociation.atlassian.net/browse/OS-737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add: generic functions

.github/workflows/reusable-check-tag.yml
=> ci: fixes check tag to ignore semver additions

.github/workflows/configs-tests.yml, .github/workflows/contracts-tests.yml, .github/workflows/reusable-publish.yml, .github/workflows/sdk-tests.yml, configs/package.json, configs/yarn.lock
- fixes publish workflows to install deps in the right directory
- renames test workflows to be more meaningful
- adds workflow to test configs package
Task ID: [OS-992](https://aragonassociation.atlassian.net/browse/OS-992)
[OS-992]: https://aragonassociation.atlassian.net/browse/OS-992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ci: fixes publish workflows

subgraph/CHANGELOG.md
PR for releasing the new subgraph version
=> feat: release subgraph commons

.github/pull_request_template.md, contracts/CHANGELOG.md, contracts/package.json, contracts/yarn.lock
Task ID: surfaced in [OS-1273](https://aragonassociation.atlassian.net/browse/OS-1273)
[OS-1273]: https://aragonassociation.atlassian.net/browse/OS-1273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: bump OZ to v4.9.6

configs/package.json, contracts/src/dao/IDAO.sol, contracts/src/permission/PermissionLib.sol, contracts/src/permission/auth/DaoAuthorizable.sol, contracts/src/permission/auth/DaoAuthorizableUpgradeable.sol, contracts/src/permission/condition/IPermissionCondition.sol, contracts/src/permission/condition/PermissionCondition.sol, contracts/src/permission/condition/PermissionConditionUpgradeable.sol, contracts/src/plugin/IPlugin.sol, contracts/src/plugin/Plugin.sol, contracts/src/plugin/PluginCloneable.sol, contracts/src/plugin/PluginUUPSUpgradeable.sol, contracts/src/plugin/extensions/governance/Addresslist.sol, contracts/src/plugin/extensions/membership/IMembership.sol, contracts/src/plugin/extensions/proposal/IProposal.sol, contracts/src/plugin/extensions/proposal/Proposal.sol, contracts/src/plugin/extensions/proposal/ProposalUpgradeable.sol, contracts/src/plugin/setup/IPluginSetup.sol, contracts/src/plugin/setup/PluginSetup.sol, contracts/src/plugin/setup/PluginUpgradeableSetup.sol, contracts/src/utils/deployment/ProxyFactory.sol, contracts/src/utils/deployment/ProxyLib.sol, contracts/src/utils/versioning/IProtocolVersion.sol, contracts/src/utils/versioning/ProtocolVersion.sol, contracts/src/utils/versioning/VersionComparisonLib.sol, sdk/package.json
To prepare the contracts for an upcoming (pre)-release, we adapt the author names after the AA dissolution
Task: [OS-1289](https://aragonassociation.atlassian.net/browse/OS-1289)
- chore
[OS-1289]: https://aragonassociation.atlassian.net/browse/OS-1289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: change authors after AA dissolution

README.md, contracts/README.md
Task ID: [OS-1118](https://aragonassociation.atlassian.net/browse/OS-1118)
[OS-1118]: https://aragonassociation.atlassian.net/browse/OS-1118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: added and improved `README.md`s

configs/CHANGELOG.md, configs/package.json, configs/src/deployments/contracts.ts, configs/src/deployments/json/sepolia.json, configs/src/deployments/json/zksyncSepolia.json, configs/src/deployments/types.ts, configs/src/networks/networks.ts
Fixes the errors on the PR adding the zksync network. 
We should either merge #85 before or just keep this one.
Task ID: [OS-No-ref](https://aragonassociation.atlassian.net/browse/OS-?)
=> fix: zksync network configuration

configs/CHANGELOG.md, configs/package.json, configs/src/deployments/contracts.ts, configs/src/deployments/json/sepolia.json, configs/src/deployments/json/zksyncSepolia.json, configs/src/deployments/types.ts, configs/src/networks/networks.ts, configs/src/networks/types.ts
=> chore: added zksync sepolia support

configs/CHANGELOG.md, configs/package.json, configs/src/deployments/contracts.ts, configs/src/deployments/json/zksyncMainnet.json, configs/src/networks/networks.ts, configs/src/networks/types.ts
=> chore: added zksync mainnet support

configs/CHANGELOG.md, configs/package.json, configs/src/deployments/contracts.ts, configs/src/deployments/json/holesky.json, configs/src/deployments/json/sepolia.json, configs/src/networks/networks.ts, configs/src/networks/types.ts
Add holesky support configuration
Task ID: [OS-1411](https://aragonassociation.atlassian.net/browse/OS-1411)
[OS-1411]: https://aragonassociation.atlassian.net/browse/OS-1411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Add holesky support configuration

contracts/src/plugin/Plugin.sol, contracts/src/plugin/PluginCloneable.sol, contracts/src/plugin/PluginUUPSUpgradeable.sol, contracts/test/plugin/plugin-clonable.ts, contracts/test/plugin/plugin-uups-upgradeable.ts, contracts/test/plugin/plugin.ts
=> fallback to dao as a target if no target set

contracts/src/mocks/permission/condition/extensions/RuledConditionMock.sol, contracts/test/permission/condition/extensions/always-true-condition.ts, contracts/test/permission/condition/extensions/ruled-condition.ts, contracts/test/utils/condition/condition.ts
=> Feat: add missing tests

contracts/CHANGELOG.md, contracts/src/mocks/plugin/extensions/proposal/ProposalMock.sol, contracts/src/mocks/plugin/extensions/proposal/ProposalUpgradeableMock.sol, contracts/src/plugin/extensions/proposal/IProposal.sol, contracts/src/plugin/extensions/proposal/Proposal.sol, contracts/src/plugin/extensions/proposal/ProposalUpgradeable.sol, contracts/test/executors/executor.ts
=> add hasSucceeded instead of

contracts/src/mocks/plugin/extensions/proposal/ProposalMock.sol, contracts/src/mocks/plugin/extensions/proposal/ProposalUpgradeableMock.sol, contracts/src/plugin/extensions/proposal/IProposal.sol, contracts/src/plugin/extensions/proposal/Proposal.sol, contracts/src/plugin/extensions/proposal/ProposalUpgradeable.sol
=> feature: add execute and canExecute in iproposal

contracts/hardhat.config.ts, contracts/package.json
=> fix: heap out of memory error

.github/workflows/formatting-linting.yml, configs/.eslintrc.yml, contracts/.eslintrc.yml, contracts/docs/config.js
=> prettier and eslints fixed

.github/workflows/sdk-tests.yml
=> fix: fix sdk-test workflow

.env.example, .github/workflows/artifacts-build.yml, .github/workflows/configs-tests.yml, .github/workflows/contracts-tests.yml, .github/workflows/formatting-linting.yml, .github/workflows/sdk-tests.yml, .github/workflows/subgraph-tests.yml, sdk/CHANGELOG.md, sdk/package.json, sdk/src/ipfs.ts, sdk/test/unit/ipfs.test.ts, sdk/yarn.lock
Updating `uploadToPinata()` to receive an explicit parameter, rather than `process.env.PUB_PINATA_JWT`
=> Fix: Upload to IPFS with an explicit JWT

.github/workflows/sdk-publish.yml
=> feat: add pinnata

.github/workflows/packages-release.yml, .github/workflows/sdk-publish.yml
=> Fix: define pinnata on sdk publish workflow

README.md
Adding an audit report link to the readme
=> Adding an audit report link to the readme

configs/src/deployments/json/zksyncSepolia.json
=> Feat/update zksyncSepolia to protocol 1.4.0

configs/src/deployments/json/sepolia.json
=> Add address for upgrade 1.4.0 on Sepolia

configs/src/deployments/json/arbitrumSepolia.json
=> Add address for upgrade 1.4.0 on ArbitrumSepolia

configs/src/deployments/json/mainnet.json
=> Feat/update mainnet to protocol 1.4.0

configs/src/deployments/json/baseMainnet.json
=> Feat/update base to protocol 1.4.0

configs/src/deployments/json/linea.json
=> Feat/update linea to protocol 1.4.0

configs/src/deployments/json/zksyncMainnet.json
=> Feat/update zksync to protocol 1.4.0

configs/src/deployments/json/arbitrum.json
=> Feat/update arbitrum to protocol 1.4.0

configs/src/deployments/json/polygon.json
=> Feat/update polygon to protocol 1.4.0
